### ISSUE TITLE
Does RPA-Python works on Windows 2012 R2 - it should, pending checks

### ISSUE THREAD

**Issue by jooeey** [tebelorg/RPA-Python#351]
I run a demo on a server( Windows 2012 R2 x64) with code like this:

```
r.init(visual_automation=True, chrome_browser=False) 
r.click('example.png')

```
then ,tagui window throw an exception and quit at once . I found the error message in tagui.log(location:%USERPROFILE%\AppData\Roaming\tagui\src\tagui.sikuli)
```

[tagui] START  - listening for inputs

[tagui] INPUT  - [1] present file_icon.png
[tagui] ACTION - present file_icon.png
[error] script [ tagui ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\tagui\src\tagui.sikuli\tagui.py", line 524, in <module>
    intent_result_value = parse_intent(tagui_intent)
  File "C:\Users\admin\AppData\Roaming\tagui\src\tagui.sikuli\tagui.py", line 476, in parse_intent
    return visible_intent(script_line);
  File "C:\Users\admin\AppData\Roaming\tagui\src\tagui.sikuli\tagui.py", line 400, in visible_intent
    if exists(params):
	at org.opencv.imgproc.Imgproc.matchTemplate_1(Native Method)
	at org.opencv.imgproc.Imgproc.matchTemplate(Imgproc.java:2612)
	at org.sikuli.script.Finder$Finder2.doFindMatch(Finder.java:898)
	at org.sikuli.script.Finder$Finder2.doFind(Finder.java:868)
	at org.sikuli.script.Finder$Finder2.find(Finder.java:617)
	at org.sikuli.script.Finder.find(Finder.java:280)
	at org.sikuli.script.Region.runFinder(Region.java:2958)
	at org.sikuli.script.Region.doFind(Region.java:2894)
	at org.sikuli.script.Region.access$300(Region.java:23)
	at org.sikuli.script.Region$RepeatableFind.run(Region.java:3175)
	at org.sikuli.script.Region$Repeatable.repeat(Region.java:3126)
	at org.sikuli.script.Region.exists(Region.java:2442)
	at org.sikuli.script.Region.exists(Region.java:2466)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
java.lang.Exception: java.lang.Exception: unknown exception

IDE terminated: returned: 1

```
I did not find a solution on the net, how can you solve this problem, thank you.

**Comment by kensoh** [comment]
Hi @jooeey I have not come across this error reported by users. Some ideas to try -

1. delete the TagUI engine by doing this. print(r.tagui_location()), there should be a tagui folder in that location, delete it
2. re-install OpenJDK to isolate if the issue is due to Java - https://aws.amazon.com/corretto (choose 64-bit v8 or later)

Try again to see if the same error happens.
