### ISSUE TITLE
failed downloading error

### ISSUE THREAD

**Issue by alx-xlx** [tebelorg/RPA-Python#542]
I am trying to run this on the raspi5-arm64 and I get the error as below. I am running it fresh

```
from time import sleep
import rpa as r

# r.setup() # This will start the download of TAGUI

r.dump(r.load('/home/pi/.tagui/src/tagui').replace('"google-chrome"', '"chromium-browser"'), '/home/pi/.tagui/src/tagui')

r.error(True)
r.init()
r.url('https://www.google.com')
r.wait(delay_in_seconds=10)
try:
    r.type('//*[@name="q"]', 'decentralisation[enter]')
except Exception as e:
    print("ERROR")
    print(e)
r.close()
```

### Error
```
[Errno 2] No such file or directory: '/home/pi/.tagui/src/tagui.sikuli/tagui.py'
Traceback (most recent call last):
  File "/home/pi/myenv/lib/python3.11/site-packages/tagui.py", line 1519, in download
    import urllib.request; urllib.request.urlretrieve(download_url, filename_to_save)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.tagui/src/tagui.sikuli/tagui.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/tmp/rpa-setup.py", line 12, in <module>
    r.init()
  File "/home/pi/myenv/lib/python3.11/site-packages/tagui.py", line 502, in init
    if not _tagui_delta(tagui_directory): return False
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/myenv/lib/python3.11/site-packages/tagui.py", line 218, in _tagui_delta
    if not download(tagui_delta_url, tagui_delta_file): return False
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/myenv/lib/python3.11/site-packages/tagui.py", line 1523, in download
    show_error('[RPA][ERROR] - failed downloading from ' + download_url + '...')
  File "/home/pi/myenv/lib/python3.11/site-packages/tagui.py", line 288, in show_error
    raise Exception(error_message)
Exception: [RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui.sikuli/tagui.py...

```

**Comment by kensoh** [comment]
Hi @alx-xlx, thanks for raising this! There seems to be problem downloading or accessing github.com. Can you try with another Raspberry Pi with Internet access, or try the Raspberry Pi setup guide on the rpa package GitHub homepage?
